import chalk from "chalk";
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
console.log(chalk.green("PASS !"));
